# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Instalação

Para instalar o NumPy, você pode usar o pip, que é o gerenciador de pacotes do Python.

```python
pip install numpy
```

## Arrays

Um array é uma estrutura de dados que armazena valores do mesmo tipo. Em Python, isso é uma grande vantagem porque economiza espaço e permite operações mais eficientes. Vamos criar um array.



In [5]:
import numpy as np

# criação de um array
cria_array = np.array([1, 2, 3, 4, 5])
print(cria_array)

[1 2 3 4 5]


In [15]:
# "Slace" --> [x, y, z]
print(cria_array[0])
print(cria_array[-1]) # coloca o último elemento
print(cria_array[1:4])
print(cria_array[0:-1]) # exclui o ultimo elemento
print(cria_array[0:-1:2])
print(cria_array[0::2])
print(cria_array[::2])
print(cria_array[::])
print(cria_array[::-1])

1
5
[2 3 4]
[1 2 3 4]
[1 3]
[1 3 5]
[1 3 5]
[1 2 3 4 5]
[5 4 3 2 1]
